#!/bin/sh

# Mount all necessary dev/proc filesystems from live crux
mount --bind /dev /mnt/dev
mount --bind /tmp /mnt/tmp
mount --bind /run /mnt/run
mount -t proc proc /mnt/proc
mount -t sysfs none /mnt/sys
mount -t devpts -o noexec,nosuid,gid=tty,mode=0620 devpts /mnt/dev/pts

if grep -qs /sys/firmware/efi/efivars /proc/mounts; then
	mount --bind /sys/firmware/efi/efivars /mnt/sys/firmware/efi/efivars
fi

# Enter chroot and run commands for qubes' configuration
chroot /mnt /bin/bash -x <<EOF

# install some default locales
mkdir -p /usr/share/locale
localedef -i en_US -f ISO-8859-1 en_US
localedef -i en_US -f ISO-8859-1 en_US.ISO-8859-1
localedef -i en_US -f UTF-8 en_US.UTF-8

# install grub2
grub-install /dev/xvda
grub-mkconfig > /boot/grub/grub.cfg

# because PAM will want the passwd changed first
sed -i '1s#0#1#' /etc/shadow

# create users, configure
groupadd --force --system --gid 98 qubes
useradd -m -U --shell /bin/bash user
usermod -a --groups qubes user
usermod -L user
usermod -p '' root
usermod -a -G wheel user

# revert shadow change so error shows up forcing chg
sed -i '1s#1#0#' /etc/shadow

# some qubes directories
mkdir -p /etc/qubes/protected-files.d
mkdir -p /etc/skel

dbus-uuidgen --ensure=/etc/machine-id

# disable crux' net config in favor of qubes'
sed -i 's# net # #' /etc/rc.conf

EOF

