#!/bin/sh

# Copying kernel config from outer environment into chroot
# this copy allows any users who make modifications direct to the kernel config
# to take effect without having to switch over to manual.
# In all other cases, this copy should have no effect (same files)
echo "copying generic stripped kernel to chroot (/usr/ports/qubes-crux/helpers)..."
cp kernel.config /mnt/usr/ports/qubes-crux/helpers/kernel.config

name=$(ls -dAv1 /mnt/usr/src/*/)
nums=${name#*-}
VERS=${nums%?}

# Enter the chroot and clean the source tree, build the kernel
chroot /mnt /bin/bash -x <<EOF

if [ ! -f "/usr/src/linux-$VERS/.config" ]; then
	echo "cleaning linux source tree and copying back config..."

	cd /usr/src/linux-"$VERS"
	make mrproper
	cp -v /usr/ports/qubes-crux/helpers/kernel.config \
	      /usr/src/linux-$VERS/.config
fi

cd /usr/ports/qubes-crux/helpers
/bin/bash /usr/ports/qubes-crux/helpers/kernel_build.sh

EOF

