#!/bin/sh

# Enter chroot and run commands for qubes' configuration
chroot /mnt /bin/bash -x <<EOF

echo 'nameserver 10.139.1.1' >> /etc/resolv.conf

cd /usr/ports/qubes-crux/helpers
/bin/bash /usr/ports/qubes-crux/helpers/qubes_build.sh

echo 'chmod 1777 /dev/shm' >> /etc/rc.local
echo 'add_dracutmodules+="qubes-vm qubes-vm-simple qubes-vm-modules"' > /etc/dracut.conf.d/qubes.conf
dracut --force
/usr/ports/qubes-crux/helpers/package_dom0_kernel.sh
grub-mkconfig > /boot/grub/grub.cfg

EOF

