#!/bin/bash

name=$(ls -dAv1 /mnt/usr/src/*/)
nums=${name#*-}
VERS=${nums%?}

if [ ! -f "/mnt/usr/src/linux-$VERS/.config" ]; then
	cp -v /mnt/usr/ports/qubes-crux/helpers/kernel.config \
	      /mnt/usr/src/linux-$VERS/.config
fi

echo "cd /usr/src/linux-$VERS"
echo "make menuconfig"
echo "cd /usr/ports/qubes-crux/helpers"
echo "./kernel_build.sh #includes modules,headers,bzimage"
chroot /mnt /usr/bin/env PS1="(chroot) # ${PS1}" /bin/bash

