#!/bin/sh
#
# /etc/rc.d/qubes-setup-ip: initialize network devices and assign IP addresses
#

INTERFACE=eth0
case $1 in
start)
	echo "Setting up network device $INTERFACE..."
	INTERFACE=$INTERFACE /usr/lib/qubes/setup-ip
	;;
stop)
	echo "Disabling $INTERFACE network device..."
	ip addr flush dev $INTERFACE
	/sbin/ifconfig $INTERFACE down		
	;;
restart)
	$0 stop
	$0 start
	;;
status)
	echo "Network device $INTERFACE is $(cat /sys/class/net/$INTERFACE/operstate)"
	;;
*)
	echo "usage: $0 [start|stop|restart|status]"
	;;
esac

# End of file
